[tools]
ruby = "3.3.4"
kubectl = "1.30.1"
usage = "0.2.0"
awscli = "2.15.53"
go = "1.16.3"
kubectx = "0.9.3"
node = "20.14.0"
python = "3.9.4"
terraform = "1.8.2"
packer = "1.7.2"
rust = "1.77.2"

[settings]
asdf_compat = true
