[tools]
ruby = "latest"
kubectl = "1.30.1"
usage = "0.2.0"
awscli = "2.15.53"
go = "1.16.3"
kubectx = "0.9.3"
node = "18.15.0"
python = "3.9.4"
terraform = "1.2.3"
packer = "1.7.2"
rust = "1.77.2"

[settings]
asdf_compat = true
