
[terminal.shell]
args = ['--login']
program = "/bin/zsh"

[cursor]
style = "Beam"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
option_as_alt = "Both"
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 0

#[window.dimensions]
#columns = 90
#lines = 25

# [colors.normal]
# black = "#21222c"
# red = "#ff5555"
# green = "#50fa7b"
# yellow = "#f1fa8c"
# blue = "#bd93f9"
# magenta = "#ff79c6"
# cyan = "#8be9fd"
# white = "#f8f8f2"
#
[colors.primary]
background = "#282828"
# foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[terminal]
